# Generated by Django 4.2.1 on 2023-07-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_reg', '0002_user_cred_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uname', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='User_cred',
        ),
    ]
